### ISSUE TITLE
Subdomains is not being identified correctly

### ISSUE THREAD

**Issue by gapinto** [needle-innovision/nestjs-tenancy#3]
For example:

I'm using postman to simulate a subdomain: gap.tenancy.com.br
The subdomain returned is `tenancy`, where the correct subdomain should be gap.

I have edited my etc/hosts to something like this:

127.0.0.1       gap.tenancy.com.br

https://github.com/needle-innovision/nestjs-tenancy/blob/117280bb2ce508a0f1a4336715c78ffe093522ec/lib/tenancy-core.module.ts#L176

**Comment by sandeepsuvit** [comment]
Hi @gapinto 

Did you try setting the configuration `isTenantFromSubdomain` like below when you are using subdomain based tenant

```typescript
TenancyModule.forRootAsync({
      imports: [TenantModule],
      useFactory: async (cfs: ConfigService, tVal: CustomTenantValidator) => {
        return {
          // To identify tenant information from the url
          isTenantFromSubdomain: true,
          options: () => {},
          uri: (tenantId: string) => `mongodb://localhost/test-tenant-${tenantId}`,
          // Custom validator to check if the tenant exist in common database
          validator: (tenantId: string) => tVal.setTenantId(tenantId),
        }
      },
      inject: [ConfigService, CustomTenantValidator],
    }),
```

**Comment by sandeepsuvit** [comment]
@gapinto i have published a new version `v1.0.9` with a small fix for multi-level subdomains. Please let me know if that fixes your issue.

**Comment by sandeepsuvit** [comment]
@gapinto can you confirm if this is working for you so that i can close this issue pls?

**Comment by sandeepsuvit** [comment]
Closing this issue as there was no followup. Hope the new version addresses the fix.
