### ISSUE TITLE
NestJS v9?

### ISSUE THREAD

**Issue by manojchandrashekar** [needle-innovision/nestjs-tenancy#32]
Hi @sandeepsuvit. Found the library very useful. Thank you.

But it fails to install on the latest nestjs version because of peer dependency failure.

I tried locally on v9 and it works fine (without extensive testing). Maybe you just need to update the peer dependencies?

**Comment by sandeepsuvit** [comment]
@manojchandrashekar thanks for writing in. The upgrade to v9 is complete. Please check the docs for installation instructions
