### ISSUE TITLE
Update Documentation [README file & NPM example]

### ISSUE THREAD

**Issue by SamLevinSE** [needle-innovision/nestjs-tenancy#33]
Hey,

Checking the documentation of NestJS, the value assigned to the load property is an array, however, in the example you provided you directly pass the configuration. This produces a type error. From docs:
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/37846034/198080992-a391b109-983f-4a4d-b266-74c4b039a7c8.png">

The update will be like this:

`
ConfigModule.forRoot({
            isGlobal: true,
            load: [configuration],
})
`

Best,
Sam

**Comment by sandeepsuvit** [comment]
@SamLevinSE thanks for writing in. I have updated the docs.
