### ISSUE TITLE
Lifecycle Events and Task Scheduling not working

### ISSUE THREAD

**Issue by canhhungit** [needle-innovision/nestjs-tenancy#43]
Hi @sandeepsuvit ,

I changed MongooseModule to TenancyModule then i got warning like this.

Task Scheduling and onModuleInit not working. Please check

![image](https://user-images.githubusercontent.com/32119496/208821808-b946c5ac-4aba-4d70-bdee-a4fdb60f196a.png)

**Comment by canhhungit** [comment]
Project to test proplem

[https://github.com/canhhungit/NestJS-tenancy](https://github.com/canhhungit/NestJS-tenancy)

**Comment by sandeepsuvit** [comment]
@canhhungit thanks for writing in. I checked your code. Seems like you are using a cron trigger inside your service class. The way the library is designed and the tenant is resolved is via a `Request` scoped object that comes from the client applications. In case of cron triggers they are originated from the backend application itself and not via a client side request. Hence there is no way the module can understand and resolve the correct tenant schema model. I am guessing for this cron cases the connections needs to be manually resolved and used.

**Comment by canhhungit** [comment]
Thank you @sandeepsuvit. While waiting from your  response, i understand proplem as you said. 
I resolve it menual with connection string with monggose

**Comment by sandeepsuvit** [comment]
@canhhungit thats great and sorry for the delayed response :)
