### ISSUE TITLE
Subdomains not identified by default.

### ISSUE THREAD

**Issue by jarrilla** [needle-innovision/nestjs-tenancy#6]
Similar (or same) issue as here: https://github.com/needle-innovision/nestjs-tenancy/issues/3#issue-696412315

When using 
`isTenantFromSubdomain: true`
Tenants are not being identified.

This seems to be an issue with subdomains not being read properly by nestjs.

**Comment by sandeepsuvit** [comment]
@jarrilla Thanks for the note. Reviewing your PR. Will provide an update once approved.

**Comment by jarrilla** [comment]
This was an issue with testing in a local environment.

See https://github.com/needle-innovision/nestjs-tenancy/pull/7#issuecomment-757958355

**Comment by sandeepsuvit** [comment]
Thanks @jarrilla
